"""empty message

Revision ID: 8e6eb8a8fd5d
Revises: 
Create Date: 2019-10-24 14:30:32.217892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6eb8a8fd5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('sourdough',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('alive', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sourdough_birthday'), 'sourdough', ['birthday'], unique=False)
    op.create_table('feeding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sourdough_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sourdough_id'], ['sourdough.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feeding_timestamp'), 'feeding', ['timestamp'], unique=False)
    op.create_table('reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('reading', sa.Integer(), nullable=False),
    sa.Column('normalizedReading', sa.Numeric(), nullable=True),
    sa.Column('feeding_id', sa.Integer(), nullable=True),
    sa.Column('sourdough_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feeding_id'], ['feeding.id'], ),
    sa.ForeignKeyConstraint(['sourdough_id'], ['sourdough.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_timestamp'), 'reading', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_timestamp'), table_name='reading')
    op.drop_table('reading')
    op.drop_index(op.f('ix_feeding_timestamp'), table_name='feeding')
    op.drop_table('feeding')
    op.drop_index(op.f('ix_sourdough_birthday'), table_name='sourdough')
    op.drop_table('sourdough')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
