"""empty message

Revision ID: b26df40cd11f
Revises: 8e6eb8a8fd5d
Create Date: 2019-10-24 15:15:46.941820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26df40cd11f'
down_revision = '8e6eb8a8fd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('filename', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading', 'filename')
    # ### end Alembic commands ###
